# Generated by Django 3.0.3 on 2021-09-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='product',
            field=models.ManyToManyField(to='api.Product'),
        ),
        migrations.RemoveField(
            model_name='saleorder',
            name='product',
        ),
        migrations.AddField(
            model_name='saleorder',
            name='product',
            field=models.ManyToManyField(to='api.Product'),
        ),
    ]
