# Generated by Django 3.0.3 on 2021-09-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210922_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='units',
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
