# Generated by Django 3.0.3 on 2021-09-22 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customer_order_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Order'),
        ),
    ]
